- name: Installing nginx
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 86400
    name:
      - nginx

- name: Configure vhost
  notify: restart nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
