- name: Installing JRE
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 86400
    name: openjdk-7-jre

- name: Installing utilities needed for Wowza
  apt:
    state: present
    name:
      - expect
      - rsync

- name: Download WowzaStreamingEngine {{ wowza_version }}
  get_url:
    url: https://www.wowza.com/downloads/WowzaStreamingEngine-{{ wowza_version | regex_replace('\.', '-') }}/WowzaStreamingEngine-{{ wowza_version }}-linux-x64-installer.run
    dest: /home/vagrant/WowzaStreamingEngine-{{wowza_version }}-linux-x64-installer.run
    sha256sum: 254187143e5ca88cf8ac0f4b59accef7c2d835aa9f6f219e2e271486155b24c5
    mode: 0744

- name: Push installation script
  template: src=wowza.exp.j2 dest=/home/vagrant/wowza.exp mode=0755

- name: Run installation
  command: /home/vagrant/wowza.exp
  register: installed
  args:
    chdir: /home/vagrant
    creates: "{{ dir }}/conf/Server.license"

- name: Fixed borked directory permissions
  command: find "{{ dir }}/" -type d -exec chmod 755 {} +
  when: installed|changed

- name: Fixed borked file permissions
  command: find "{{ dir }}/" -type f -regex '.*\.\(txt\|xml\|properties\|password\|access\|jar\|png\|so\|java\|ttf\|html\|js\|as\|pdf\|service\|desktop\|mo\|gif\|swf\|css\|user\|cs\|csproj\|fla\|mxml\|policy\|xaml\|db\|config\|dll\|war\|mp4\)' -exec chmod 644 {} +
  when: installed|changed

- name: Copying jars to shared folder for building
  when: installed|changed
  synchronize:
    src: "{{ dir }}/lib/"
    dest: "/vagrant/lib"
